---
name: build docker image

on:
  workflow_dispatch:
    inputs:
      context:
        description: "app folder with Dockerfile, f.e. postgres-db-init"
        required: true
        type: string

jobs:
  docker-build:
    uses: "strg-at/github-workflows/.github/workflows/docker-build.yaml@v0.3.0"
    with:
      runner: '["ubuntu-latest"]'
      context: ${{ inputs.context }}
