---
name: renovate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: dry-run
        required: false
        type: string
        default: "false"
      log-level:
        description: log-level
        required: false
        type: string
        default: info
  schedule:
    - cron: "0 */3 * * 1-4"
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/renovate/**.json5
      - .github/workflows/renovate.yaml

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    uses: strg-at/github-workflows/.github/workflows/run-renovate.yaml@ac385260abbb841598c1740ae222d4f1ab3c9b40 # v1.9.0
    with:
      runner: '["ubuntu-latest"]'
      configuration-file: .github/renovate-bot.json5
      dry-run: ${{ inputs.dry-run || 'false' }}
      log-level: ${{ inputs.log-level || 'info' }}
    secrets:
      github-app-id: ${{ secrets.STRG_PUBLIC_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.STRG_PUBLIC_BOT_GITHUB_PEM }}
